# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1603617e14148d8e750f2c9b47dcc77ad8b47577caf2534d3c77207034c0e8fc6e9e4a3763d9373b8c9e4d65ae66fa213fb377888136b5bfdbb360157e283b3
  username

test:
  secret_key_base: b7a1fb229c6b7ec2afce7b61189df0b6106627d5c17dafa84d2f3a72be33de5da645b4971ba5cecddae84cc5f435160ac42f84ac112bbafcca1f68fd69939bd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
